spring:
<<<<<<< HEAD
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    showsql: false
=======
  jpa:
>>>>>>> 641e1e3cfa2afb78e5f2e7e396749840bc9ead62
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 123@Mudar123
  jackson:
    default-property-inclusion: non_null