spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    showsql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 123@Mudar123
  jackson:
    default-property-inclusion: non_null